### ISSUE TITLE
Make it live on GitHub pages

### ISSUE THREAD

**Issue by keybits** [fionnualasolomon/Guess-my-number#1]
To make this live on GitHub pages is quite simple as it has an `index.html` file in the root of the project.

Go to 'Settings' for the project and 'Pages' - then select `Main` as the branch and `root` and save. That's it  - it'll give you a URL for the site and you can share it with the world.

**Comment by fionnualasolomon** [comment]
This is done - here is the link https://fionnualasolomon.github.io/Guess-my-number/
